services:
    # PHP Application
    workspace:
        build:
            context: .
            dockerfile: docker/Dockerfile
        image: web-workspace
        container_name: web-workspace
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - laravel-network
        depends_on:
            - mysql
            - redis
        user: "1000:1000"

    # Nginx Web Server
    nginx:
        image: nginx:alpine
        container_name: web-nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel-network
        depends_on:
            - workspace

      # MySQL Database
    mysql:
      image: mysql:8.0
      container_name: web-mysql
      restart: unless-stopped
      environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} # Use a secure password, can be set in a .env file
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes' # Set to 'no' for production
      volumes:
        - web-data:/var/lib/mysql
      networks:
        - laravel-network
      ports:
        - "3306:3306" # Standard MySQL port

  # PhpMyAdmin (Database GUI)
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: web-phpmyadmin
      restart: unless-stopped
      environment:
        PMA_HOST: mysql # Links to the service name 'mysql'
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      ports:
        - "8080:80" # Access via http://localhost:8080
      networks:
        - laravel-network
      depends_on:
        - mysql

    # Redis
    redis:
        image: redis:alpine
        container_name: web-redis
        restart: unless-stopped
        networks:
            - laravel-network
        ports:
            - "6379:6379"

networks:
    laravel-network:
        driver: bridge

volumes:
    web-data:
